Repository dongsooop/backend, pull requests merged in 2025-07, with the labels that each got.

#100 마이페이지 사용자 데이터 조회 기능 구현
  src/main/java/com/dongsoop/dongsoop/marketplace/repository/MarketplaceBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/marketplace/repository/MarketplaceBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/mypage/controller/MyPageController.java
  src/main/java/com/dongsoop/dongsoop/mypage/dto/MyRecruitmentOverview.java
  src/main/java/com/dongsoop/dongsoop/mypage/dto/MyRecruitmentOverviewResponse.java
  src/main/java/com/dongsoop/dongsoop/mypage/dto/OpenedMarketplace.java
  src/main/java/com/dongsoop/dongsoop/mypage/service/MyPageService.java
  src/main/java/com/dongsoop/dongsoop/mypage/service/MyPageServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/RecruitmentType.java
  src/main/java/com/dongsoop/dongsoop/recruitment/dto/RecruitmentDetails.java
  src/main/java/com/dongsoop/dongsoop/recruitment/dto/RecruitmentOverview.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/controller/ProjectBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/dto/ProjectBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/dto/ProjectBoardOverview.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/entity/ProjectApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/projection/ProjectRecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/projection/RecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/projection/StudyRecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/projection/TutoringRecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/controller/StudyBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/dto/StudyBoardOverview.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/entity/StudyApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/controller/TutoringBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/dto/TutoringBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/entity/TutoringApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringBoardServiceImpl.java
Labels: Feature

#102 신고 및 제재 시스템 구현 - 사용자 신고 및 관리자 제재 처리 기능 추가
  src/main/java/com/dongsoop/dongsoop/exception/domain/report/DuplicateReportException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/report/MemberSanctionedException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/report/ReportNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/report/ReportTargetNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/report/SanctionAlreadyExistsException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/report/SelfReportException.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/report/controller/ReportController.java
  src/main/java/com/dongsoop/dongsoop/report/dto/CreateReportRequest.java
  src/main/java/com/dongsoop/dongsoop/report/dto/ProcessSanctionRequest.java
  src/main/java/com/dongsoop/dongsoop/report/dto/ReportResponse.java
  src/main/java/com/dongsoop/dongsoop/report/dto/ReportSummaryResponse.java
  src/main/java/com/dongsoop/dongsoop/report/entity/Report.java
  src/main/java/com/dongsoop/dongsoop/report/entity/ReportFilterType.java
  src/main/java/com/dongsoop/dongsoop/report/entity/ReportReason.java
  src/main/java/com/dongsoop/dongsoop/report/entity/ReportType.java
  src/main/java/com/dongsoop/dongsoop/report/entity/SanctionType.java
  src/main/java/com/dongsoop/dongsoop/report/handler/ContentDeletionHandler.java
  src/main/java/com/dongsoop/dongsoop/report/repository/ReportRepository.java
  src/main/java/com/dongsoop/dongsoop/report/repository/ReportRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/report/repository/ReportRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/report/service/ReportService.java
  src/main/java/com/dongsoop/dongsoop/report/service/ReportServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/report/service/SanctionExecutor.java
  src/main/java/com/dongsoop/dongsoop/report/util/ReportUrlGenerator.java
  src/main/java/com/dongsoop/dongsoop/report/validator/ReportValidator.java
Labels: Feature

#107 OK 응답에 대해 No Content로 수정
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
Labels: Refactoring

#98 모집 게시판 목록 조회 시 모집 중인 상태의 글만 조회하도록 수정
  src/main/java/com/dongsoop/dongsoop/config/ClockConfig.java
  src/main/java/com/dongsoop/dongsoop/recruitment/dto/RecruitmentOverview.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/repository/RecruitmentRepositoryUtils.java
  src/main/java/com/dongsoop/dongsoop/recruitment/repository/RecruitmentRepositoryUtilsImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
Labels: Refactoring

#111 모집 게시판 지원자 목록 확인 기능 구현
  src/main/java/com/dongsoop/dongsoop/recruitment/dto/RecruitmentApplyOverview.java
  src/main/java/com/dongsoop/dongsoop/recruitment/dto/UpdateApplyStatusRequest.java
  src/main/java/com/dongsoop/dongsoop/recruitment/entity/RecruitmentApplyStatus.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/controller/ProjectApplyController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/entity/ProjectApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/exception/ProjectBoardNotFound.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepository.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectApplyService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/controller/StudyApplyController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/entity/StudyApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/exception/StudyBoardNotFound.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepository.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyApplyService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/controller/TutoringApplyController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/entity/TutoringApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/exception/TutoringBoardNotFound.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepository.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringApplyService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringApplyServiceImpl.java
Labels: Feature

#114 모집 게시글 지원자 세부 지원 정보 조회
  src/main/java/com/dongsoop/dongsoop/recruitment/dto/ApplyDetails.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/controller/ProjectApplyController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/exception/ProjectApplyNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectApplyService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/projection/ProjectRecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/projection/RecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/projection/StudyRecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/projection/TutoringRecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/controller/StudyApplyController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/exception/StudyApplyNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyApplyService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/controller/TutoringApplyController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/exception/TutoringApplyNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringApplyService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringApplyServiceImpl.java
Labels: Feature

#116 회원탈퇴 불가 문제 수정
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
Labels: bug

#118 DB 조회 결과 중복 제거
  src/main/java/com/dongsoop/dongsoop/recruitment/board/dto/RecruitmentDetails.java
Labels: bug

#120 지원자 중복 제거
  src/main/java/com/dongsoop/dongsoop/recruitment/board/projection/ProjectRecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/projection/StudyRecruitmentProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/projection/TutoringRecruitmentProjection.java
Labels: bug

#117 필터 토큰 검증 로직 수정
  src/main/java/com/dongsoop/dongsoop/jwt/JwtUtil.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/JWTException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/NotAccessTokenException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/NotRefreshTokenException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/RefreshTokenNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenExpiredException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenMalformedException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenRoleNotAvailableException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenSignatureException.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenUnsupportedException.java
  src/main/java/com/dongsoop/dongsoop/jwt/filter/JwtFilter.java
Labels: bug

#121 모집 게시글 태그 필수 적용
  src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
  src/main/java/com/dongsoop/dongsoop/recruitment/validation/annotation/BoardTag.java
  src/main/java/com/dongsoop/dongsoop/recruitment/validation/annotation/BoardTagValidator.java
  src/main/java/com/dongsoop/dongsoop/recruitment/validation/constant/RecruitmentValidationConstant.java
Labels: Refactoring

#122 모집 지원자 상세 조회 시 제목 포함
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/dto/ApplyDetails.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/projection/ProjectRecruitmentApplyProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/projection/StudyRecruitmentApplyProjection.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/projection/TutoringRecruitmentApplyProjection.java
Labels: Refactoring

#123 본인의 모집 게시글에 셀프 지원 불가 처리
  src/main/java/com/dongsoop/dongsoop/board/Board.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/exception/ProjectOwnerCannotApplyException.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/service/ProjectApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/exception/StudyOwnerCannotApplyException.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/service/StudyApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/exception/TutoringOwnerCannotApplyException.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/service/TutoringApplyServiceImpl.java
Labels: Refactoring

#125 모집 게시판 삭제 기능
  src/main/java/com/dongsoop/dongsoop/recruitment/board/project/controller/ProjectBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/project/entity/ProjectBoard.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/project/service/ProjectBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/project/service/ProjectBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/study/controller/StudyBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/study/entity/StudyBoard.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/study/service/StudyBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/study/service/StudyBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/controller/TutoringBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/entity/TutoringBoard.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/service/TutoringBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/service/TutoringBoardServiceImpl.java
Labels: Feature

#128 신고 확인시 필요한 응답 구조 개선
  src/main/java/com/dongsoop/dongsoop/report/dto/ReportSummaryResponse.java
  src/main/java/com/dongsoop/dongsoop/report/repository/ReportRepositoryCustomImpl.java
Labels: Feature, Refactoring

#126 회원 권한 로그인 응답 값에 포함
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginMemberDetails.java
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginResponse.java
  src/main/java/com/dongsoop/dongsoop/member/exception/MemberRoleNotAvailableException.java
  src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustomImpl.java
Labels: Refactoring

#130 공지사항 파싱 시 헤더 추가
  src/main/java/com/dongsoop/dongsoop/notice/util/NoticeLinkParser.java
Labels: Refactoring

#133 feat(Report): Add Id field of reported post
  src/main/java/com/dongsoop/dongsoop/report/dto/ReportSummaryResponse.java
  src/main/java/com/dongsoop/dongsoop/report/repository/ReportRepositoryCustomImpl.java
Labels: Feature, Refactoring

#136 마이페이지 구조 수정
  src/main/java/com/dongsoop/dongsoop/mypage/dto/MyRecruitmentOverview.java
  src/main/java/com/dongsoop/dongsoop/mypage/dto/MyRecruitmentOverviewResponse.java
  src/main/java/com/dongsoop/dongsoop/mypage/dto/RecruitmentStatusType.java
  src/main/java/com/dongsoop/dongsoop/recruitment/repository/RecruitmentRepository.java
Labels: Refactoring

#137 그룹채팅방 초대 기능 및 서비스 구조 개선, 중복 코드 제거
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/CreateRoomRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/InviteUserRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoom.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoomEntity.java
  src/main/java/com/dongsoop/dongsoop/chat/exception/GroupChatOnlyException.java
  src/main/java/com/dongsoop/dongsoop/chat/exception/KickedUserInviteException.java
  src/main/java/com/dongsoop/dongsoop/chat/exception/UserAlreadyInRoomException.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatMessageService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatParticipantService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatRoomService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/chat/util/ChatCommonUtils.java
  src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java
Labels: Feature, Refactoring

#139 모집글 작성 시 자동으로 그룹 채팅방 생성 및 자동 초대 추가
  src/main/java/com/dongsoop/dongsoop/board/Board.java
  src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/service/ProjectApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/service/StudyApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/service/TutoringApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/project/service/ProjectBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/study/service/StudyBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/service/TutoringBoardServiceImpl.java
Labels: Feature

#141 이메일 인증 기능 구현
  build.gradle
  src/main/java/com/dongsoop/dongsoop/email/annotation/SchoolEmail.java
  src/main/java/com/dongsoop/dongsoop/email/annotation/SchoolEmailValidator.java
  src/main/java/com/dongsoop/dongsoop/mailverify/controller/MailVerifyController.java
  src/main/java/com/dongsoop/dongsoop/mailverify/dto/MailSendRequest.java
  src/main/java/com/dongsoop/dongsoop/mailverify/dto/MailVerifyRequest.java
  src/main/java/com/dongsoop/dongsoop/mailverify/exception/MailSendingFormatFileCannotReadException.java
  src/main/java/com/dongsoop/dongsoop/mailverify/exception/UnknownEmailEncodeException.java
  src/main/java/com/dongsoop/dongsoop/mailverify/exception/UnknownMailMessagingException.java
  src/main/java/com/dongsoop/dongsoop/mailverify/exception/UsingAllMailVerifyOpportunityException.java
  src/main/java/com/dongsoop/dongsoop/mailverify/exception/VerifyMailCodeNotAvailableException.java
  src/main/java/com/dongsoop/dongsoop/mailverify/service/MailTextGenerator.java
  src/main/java/com/dongsoop/dongsoop/mailverify/service/MailTextGeneratorImpl.java
  src/main/java/com/dongsoop/dongsoop/mailverify/service/MailVerifyService.java
  src/main/java/com/dongsoop/dongsoop/mailverify/service/MailVerifyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/member/dto/EmailValidateRequest.java
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginRequest.java
  src/main/java/com/dongsoop/dongsoop/member/dto/SignupRequest.java
  src/main/resources/static/verify-mail.html
Labels: Feature

#151 로그 파일 저장 방식 비동기 처리
  src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java
  src/main/resources/logback.xml
Labels: Refactoring
