Repository dongsooop/backend, pull requests merged in 2025-06, with the labels that each got.

#71 JWT Filter 레이어 예외처리
  src/main/java/com/dongsoop/dongsoop/exception/GlobalExceptionHandler.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/jwt/TokenMalformedException.java
  src/main/java/com/dongsoop/dongsoop/jwt/filter/JwtFilter.java
Labels: Feature

#72 채팅 매니저 권한 로직 추가 및 사용자 닉네임 필드삭제
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatSocketController.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/KickUserRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatMessage.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatMessageEntity.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoom.java
  src/main/java/com/dongsoop/dongsoop/chat/repository/InMemoryChatRepository.java
  src/main/java/com/dongsoop/dongsoop/chat/repository/RedisChatRepository.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatBackupService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
Labels: Refactoring

#74 학습 구성원 모집 게시글 전체 학과 대상 목록 조회 기능 구현
  src/main/java/com/dongsoop/dongsoop/recruitment/project/controller/ProjectBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/dto/ProjectBoardOverview.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/controller/StudyBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/dto/StudyBoardOverview.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/controller/TutoringBoardController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/dto/TutoringBoardOverview.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringBoardService.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringBoardServiceImpl.java
Labels: Feature

#76 채팅 메시지 증분 동기화 기능 추가
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/ReadStatusUpdateRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatMessage.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoom.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoomInitResponse.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/IncrementalSyncResponse.java
  src/main/java/com/dongsoop/dongsoop/chat/repository/RedisChatRepository.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatSyncService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ReadStatusService.java
  src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java
  src/main/java/com/dongsoop/dongsoop/config/RedisConfig.java
Labels: Feature, Refactoring

#81 모집 게시글 상세페이지 내 지원 여부 반환
  src/main/java/com/dongsoop/dongsoop/exception/domain/authentication/NotAuthenticationException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/project/ProjectRecruitmentAlreadyAppliedException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/study/StudyRecruitmentAlreadyAppliedException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/tutoring/TutoringRecruitmentAlreadyAppliedException.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/dto/ProjectBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepository.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/dto/StudyBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepository.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/dto/TutoringBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepository.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringBoardServiceImpl.java
Labels: Feature

#82 feat: Add chat room participant nickname return api
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
Labels: Feature

#86 시간표 기능 구현
  src/main/java/com/dongsoop/dongsoop/date/EndAtAfterStartAtValidator.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/date/TimeTypeMismatchException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/timetable/TimetableNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/timetable/TimetableNotOwnedException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/timetable/TimetableOverlapException.java
  src/main/java/com/dongsoop/dongsoop/timetable/controller/TimetableController.java
  src/main/java/com/dongsoop/dongsoop/timetable/dto/CreateTimetableRequest.java
  src/main/java/com/dongsoop/dongsoop/timetable/dto/OverlapTimetable.java
  src/main/java/com/dongsoop/dongsoop/timetable/dto/TimetableView.java
  src/main/java/com/dongsoop/dongsoop/timetable/dto/UpdateTimetableRequest.java
  src/main/java/com/dongsoop/dongsoop/timetable/dto/YearSemester.java
  src/main/java/com/dongsoop/dongsoop/timetable/entity/SemesterType.java
  src/main/java/com/dongsoop/dongsoop/timetable/entity/Timetable.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepository.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableMapper.java
  src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableService.java
  src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableServiceImpl.java
Labels: Feature

#88 활동 중인 채팅방에 새로 초대된 사용자 판단 기능 추가
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
Labels: Feature

#92 모집 게시글 생성 시 필요한 태그에 대해 어노테이션 문제 개선
  src/main/java/com/dongsoop/dongsoop/recruitment/validation/annotation/BoardTag.java
Labels: bug

#91 검증 절차 추가에 따른 테스트 케이스 Mock 추가
  src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectRecruitmentDepartmentEligibilityValidatorTest.java
  src/test/java/com/dongsoop/dongsoop/studyBoard/StudyRecruitmentDepartmentEligibilityValidatorTest.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringRecruitmentDepartmentEligibilityValidatorTest.java
Labels: Refactoring

#96 회원 탈퇴 기능 구현
  src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java
  src/main/java/com/dongsoop/dongsoop/member/controller/MemberController.java
  src/main/java/com/dongsoop/dongsoop/member/entity/Member.java
  src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepository.java
  src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
Labels: Feature

#104 장터 수정 삭제 기능 구현
  src/main/java/com/dongsoop/dongsoop/board/Board.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/marketplace/MarketplaceBoardImageAmountNotAvailableException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/member/MemberNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/marketplace/controller/MarketplaceBoardController.java
  src/main/java/com/dongsoop/dongsoop/marketplace/dto/UpdateMarketplaceBoardRequest.java
  src/main/java/com/dongsoop/dongsoop/marketplace/entity/MarketplaceBoard.java
  src/main/java/com/dongsoop/dongsoop/marketplace/entity/MarketplaceImage.java
  src/main/java/com/dongsoop/dongsoop/marketplace/repository/MarketplaceImageRepository.java
  src/main/java/com/dongsoop/dongsoop/marketplace/service/MarketplaceBoardService.java
  src/main/java/com/dongsoop/dongsoop/marketplace/service/MarketplaceBoardServiceImpl.java
Labels: Feature

#106 장터 게시판 리팩터링
  src/main/java/com/dongsoop/dongsoop/marketplace/dto/MarketplaceBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/marketplace/entity/MarketplaceBoard.java
  src/main/java/com/dongsoop/dongsoop/marketplace/repository/MarketplaceBoardRepository.java
  src/main/java/com/dongsoop/dongsoop/marketplace/repository/MarketplaceBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/marketplace/service/MarketplaceBoardServiceImpl.java
Labels: Refactoring
