Repository dongsooop/backend, pull requests merged in 2025-08, with the labels that each got.

#157 모바일 알림 기능 구현
  build.gradle
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatSocketController.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatRoomService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/department/entity/DepartmentType.java
  src/main/java/com/dongsoop/dongsoop/jwt/exception/DeviceInformationNotIncludedInHeaderException.java
  src/main/java/com/dongsoop/dongsoop/jwt/handler/JwtLogoutHandler.java
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginRequest.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/entity/MemberDevice.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/entity/MemberDeviceType.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/exception/AlreadyRegisteredDeviceException.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/exception/UnregisteredDeviceException.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepository.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceService.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notice/entity/Notice.java
  src/main/java/com/dongsoop/dongsoop/notice/entity/NoticeDetails.java
  src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/config/FCMConfig.java
  src/main/java/com/dongsoop/dongsoop/notification/config/NotificationConfig.java
  src/main/java/com/dongsoop/dongsoop/notification/exception/NotificationSendException.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java
Labels: Feature

#163 hotfix: 로그아웃 시 사용자 인증 정보 확인
  src/main/java/com/dongsoop/dongsoop/jwt/handler/JwtLogoutHandler.java
Labels: bug

#167 fix(NoticeSchedulerImpl): add Transactional from scheduled
  src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java
Labels: bug

#168 fix: WebSocket 메시지 수신 안되는 문제 및 성능 개선
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatSocketController.java
  src/main/java/com/dongsoop/dongsoop/common/config/WebSocketConfig.java
Labels: bug, Feature

#169 fix: FCM 알림 실패로 인한 메시지 처리 중단 문제 해결
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/CreateContactRoomRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatRoomService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
Labels: bug

#174 refactor(DepartmentType): change DEPT_1001 name to 동양미래대학
  src/main/java/com/dongsoop/dongsoop/department/entity/DepartmentType.java
Labels: Refactoring

#172 알림 기능 구조 개선 및 모집 게시판 알림 기능 추가
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/jwt/handler/JwtLogoutHandler.java
  src/main/java/com/dongsoop/dongsoop/member/controller/MemberController.java
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginRequest.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/controller/MemberDeviceController.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/dto/DeviceRegisterRequest.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/entity/MemberDevice.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepository.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceService.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notice/entity/NoticeDetails.java
  src/main/java/com/dongsoop/dongsoop/notice/notification/NoticeNotification.java
  src/main/java/com/dongsoop/dongsoop/notice/notification/NoticeNotificationImpl.java
  src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/constant/NotificationType.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/notification/RecruitmentApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/entity/ProjectApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/notification/ProjectApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/repository/ProjectApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/repository/ProjectApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/service/ProjectApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/entity/StudyApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/notification/StudyApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/repository/StudyApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/repository/StudyApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/service/StudyApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/entity/TutoringApply.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/notification/TutoringApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/repository/TutoringApplyRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/repository/TutoringApplyRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/service/TutoringApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/role/repository/MemberRoleRepository.java
Labels: Feature, Refactoring

#176 알림 저장 및 조회 기능 구현
  src/main/java/com/dongsoop/dongsoop/chat/notification/ChatNotification.java
  src/main/java/com/dongsoop/dongsoop/chat/notification/ChatNotificationImpl.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/dto/MemberDeviceDto.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/notice/notification/NoticeNotification.java
  src/main/java/com/dongsoop/dongsoop/notice/notification/NoticeNotificationImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/constant/NotificationType.java
  src/main/java/com/dongsoop/dongsoop/notification/controller/NotificationController.java
  src/main/java/com/dongsoop/dongsoop/notification/dto/NotificationOverview.java
  src/main/java/com/dongsoop/dongsoop/notification/dto/NotificationReadRequest.java
  src/main/java/com/dongsoop/dongsoop/notification/entity/MemberNotification.java
  src/main/java/com/dongsoop/dongsoop/notification/entity/MemberNotificationId.java
  src/main/java/com/dongsoop/dongsoop/notification/entity/NotificationDetails.java
  src/main/java/com/dongsoop/dongsoop/notification/exception/NotificationNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationDetailsRepository.java
  src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepository.java
  src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/notification/RecruitmentApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/notification/ProjectApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/controller/StudyApplyController.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/notification/StudyApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/notification/TutoringApplyNotification.java
Labels: Feature

#177 시간표 학기 기준 전체 삭제 기능 추가
  src/main/java/com/dongsoop/dongsoop/timetable/controller/TimetableController.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableService.java
  src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableServiceImpl.java
Labels: Feature

#179 다중 시간표 등록 API
  src/main/java/com/dongsoop/dongsoop/timetable/controller/TimetableController.java
  src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableService.java
  src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableServiceImpl.java
Labels: Feature

#180 지원자 알림 누락 추가
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/notification/RecruitmentApplyNotification.java
Labels: bug

#181 알림 목록 조회 시 읽지 않은 알림 수 포함
  src/main/java/com/dongsoop/dongsoop/chat/notification/ChatNotificationImpl.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepository.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceService.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notice/notification/NoticeNotificationImpl.java
  src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/controller/NotificationController.java
  src/main/java/com/dongsoop/dongsoop/notification/dto/NotificationList.java
  src/main/java/com/dongsoop/dongsoop/notification/dto/NotificationOverview.java
  src/main/java/com/dongsoop/dongsoop/notification/dto/NotificationUnread.java
  src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/notification/RecruitmentApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/notification/ProjectApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/notification/StudyApplyNotification.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/notification/TutoringApplyNotification.java
Labels: Feature

#182 알림 전송 시 유효하지 않은 토큰 제거
  src/main/java/com/dongsoop/dongsoop/chat/notification/ChatNotificationImpl.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepository.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceService.java
  src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/dto/MulticastMessageWithTokens.java
  src/main/java/com/dongsoop/dongsoop/notification/exception/ResponseSizeUnmatchedToTokenSizeException.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/apply/notification/RecruitmentApplyNotification.java
Labels: Refactoring
