Repository dongsooop/backend, pull requests merged in 2025-09, with the labels that each got.

#186 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/버그-이슈.md
  .github/ISSUE_TEMPLATE/신규-기능.md
Labels: documentation

#189 사용자 시간표 리마인드 알림 기능 구현
  src/main/java/com/dongsoop/dongsoop/notification/constant/NotificationType.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/FCMServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationSendService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationSendServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/timetable/dto/TimetableNotificationDto.java
  src/main/java/com/dongsoop/dongsoop/timetable/entity/SemesterType.java
  src/main/java/com/dongsoop/dongsoop/timetable/exception/NotAvailableMonthException.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepository.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/timetable/schedule/TimetableSchedule.java
  src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableServiceImpl.java
Labels: Feature

#195 일정 및 시간표 알림 버그 수정
  src/main/java/com/dongsoop/dongsoop/calendar/notification/CalendarNotificationImpl.java
  src/main/java/com/dongsoop/dongsoop/calendar/schedule/CalendarScheduler.java
  src/main/java/com/dongsoop/dongsoop/calendar/schedule/CalendarSchedulerImpl.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatBackupService.java
  src/main/java/com/dongsoop/dongsoop/timetable/notification/TimetableNotificationImpl.java
  src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/timetable/schedule/TimetableScheduler.java
Labels: bug

#196 특정 회원의 전체 알림 읽음 처리 구현
  src/main/java/com/dongsoop/dongsoop/notification/controller/NotificationController.java
  src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java
Labels: Feature

#198 비회원 학사일정 조회
  src/main/java/com/dongsoop/dongsoop/calendar/controller/ScheduleController.java
  src/main/java/com/dongsoop/dongsoop/calendar/service/ScheduleService.java
  src/main/java/com/dongsoop/dongsoop/calendar/service/ScheduleServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
Labels: Feature

#203 비회원을 위한 홈 API 구현
  src/main/java/com/dongsoop/dongsoop/home/controller/HomeController.java
  src/main/java/com/dongsoop/dongsoop/home/service/HomeService.java
  src/main/java/com/dongsoop/dongsoop/home/service/HomeServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/notice/repository/NoticeRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/notice/repository/NoticeRepositoryCustomImpl.java
Labels: Feature

#204 fix(home): move department to NoticeType method to dto
  src/main/java/com/dongsoop/dongsoop/notice/dto/HomeNotice.java
  src/main/java/com/dongsoop/dongsoop/notice/repository/NoticeRepositoryCustomImpl.java
Labels: bug

#209 공지사항 모바일 알림 실패 해결
  src/main/java/com/dongsoop/dongsoop/notification/service/NotificationSendServiceImpl.java
Labels: bug

#210 로그아웃 시 사용자 모바일 알림 뱃지 초기화
  src/main/java/com/dongsoop/dongsoop/jwt/handler/JwtLogoutHandler.java
Labels: Feature

#220 학과별 공지 검색
  src/main/java/com/dongsoop/dongsoop/search/controller/SearchController.java
  src/main/java/com/dongsoop/dongsoop/search/dto/BoardSearchResult.java
  src/main/java/com/dongsoop/dongsoop/search/dto/SearchDtoMapper.java
  src/main/java/com/dongsoop/dongsoop/search/entity/BoardDocument.java
  src/main/java/com/dongsoop/dongsoop/search/repository/BoardSearchRepository.java
  src/main/java/com/dongsoop/dongsoop/search/service/BoardSearchService.java
Labels: Feature

#221 어드민에 의한 채팅방 생성
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/CreateChatRoomByAdminRequest.java
Labels: Feature

#217 매니저 나가기 제한 기능 구현
  src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
  src/main/java/com/dongsoop/dongsoop/chat/exception/ManagerLeaveRestrictedException.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/chat/util/ChatCommonUtils.java
  src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/project/service/ProjectBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/study/service/StudyBoardServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/service/TutoringBoardServiceImpl.java
Labels: bug, Feature

#231 교차 학과 모집 게시글 검색 지원 및 한글-영어 혼합 텍스트 검색 개선
  src/main/java/com/dongsoop/dongsoop/search/repository/BoardSearchRepository.java
Labels: bug, Feature

#232 테스트 코드 오류 해결
  build.gradle
  src/test/java/com/dongsoop/dongsoop/DongsoopApplicationTests.java
  src/test/java/com/dongsoop/dongsoop/member/MemberLoginTest.java
  src/test/java/com/dongsoop/dongsoop/memberblock/MemberBlockTest.java
  src/test/java/com/dongsoop/dongsoop/memberblock/MemberUnblockTest.java
  src/test/java/com/dongsoop/dongsoop/notice/NoticeCrawlingTest.java
  src/test/java/com/dongsoop/dongsoop/notice/NoticeLinkParserTest.java
  src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectBoardCreateTest.java
  src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectRecruitmentDepartmentEligibilityValidatorTest.java
  src/test/java/com/dongsoop/dongsoop/studyBoard/StudyBoardCreateTest.java
  src/test/java/com/dongsoop/dongsoop/studyBoard/StudyRecruitmentDepartmentEligibilityValidatorTest.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardCreateTest.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringRecruitmentDepartmentEligibilityValidatorTest.java
Labels: bug

#233 feat(MarketplaceBoardNotFoundException): change http status bad reque…
  src/main/java/com/dongsoop/dongsoop/marketplace/exception/MarketplaceBoardNotFoundException.java
Labels: Feature

#228 장터채팅방 분리 및 채팅방 목록에 글로벌 WebSocket 알림 구현
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatSocketController.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/ChatRoomUpdateDto.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatNotificationType.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatRoomService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/chat/session/WebSocketSessionManager.java
  src/main/java/com/dongsoop/dongsoop/common/handler/websocket/StompHandler.java
  src/main/java/com/dongsoop/dongsoop/marketplace/service/MarketplaceContactServiceImpl.java
Labels: bug, Feature

#234 fix: handle null RecruitmentType in createContactMappingKey
  src/main/java/com/dongsoop/dongsoop/chat/util/ChatCommonUtils.java
Labels: bug
