Repository dongsooop/backend, pull requests merged in 2025-05, with the labels that each got.

#26 Soft Delete 구현을 위한 BaseEntity 구현
  src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java
  src/main/java/com/dongsoop/dongsoop/member/entity/Member.java
Labels: Feature

#19 튜터링 모집 게시판 엔티티 설계 구현
  src/main/java/com/dongsoop/dongsoop/board/Board.java
  src/main/java/com/dongsoop/dongsoop/board/BoardDate.java
  src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
  src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java
  src/main/java/com/dongsoop/dongsoop/tutoring/entity/TutoringBoard.java
Labels: Feature

#29 서버에서 발생하는 에러 로그를 Discord Web Hook을 통해 실시간 전송 기능 구현
  build.gradle
  src/main/resources/logback.xml
Labels: Feature

#31 fix: add automatic notice crawling scheduler with timezone sync
  src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java
Labels: enhancement

#30 튜터링 게시판 생성 및 조회 기능 구현
  build.gradle
  src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
  src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java
  src/main/java/com/dongsoop/dongsoop/common/PageableUtil.java
  src/main/java/com/dongsoop/dongsoop/config/QuerydslConfig.java
  src/main/java/com/dongsoop/dongsoop/date/DurationValidator.java
  src/main/java/com/dongsoop/dongsoop/date/EndAtAfterStartAt.java
  src/main/java/com/dongsoop/dongsoop/date/EndAtAfterStartAtValidator.java
  src/main/java/com/dongsoop/dongsoop/date/MaxDate.java
  src/main/java/com/dongsoop/dongsoop/date/MaxDateValidator.java
  src/main/java/com/dongsoop/dongsoop/date/MaxDuration.java
  src/main/java/com/dongsoop/dongsoop/date/MaxDurationValidator.java
  src/main/java/com/dongsoop/dongsoop/date/MinDuration.java
  src/main/java/com/dongsoop/dongsoop/date/MinDurationValidator.java
  src/main/java/com/dongsoop/dongsoop/date/TodayOrFuture.java
  src/main/java/com/dongsoop/dongsoop/date/TodayOrFutureValidator.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/tutoring/TutoringBoardNotFound.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/tutoring/controller/TutoringApplyController.java
  src/main/java/com/dongsoop/dongsoop/tutoring/controller/TutoringBoardController.java
  src/main/java/com/dongsoop/dongsoop/tutoring/dto/ApplyTutoringBoardRequest.java
  src/main/java/com/dongsoop/dongsoop/tutoring/dto/CreateTutoringBoardRequest.java
  src/main/java/com/dongsoop/dongsoop/tutoring/dto/TutoringBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/tutoring/dto/TutoringBoardOverview.java
  src/main/java/com/dongsoop/dongsoop/tutoring/entity/TutoringApplication.java
  src/main/java/com/dongsoop/dongsoop/tutoring/entity/TutoringBoard.java
  src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringApplicationRepository.java
  src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringBoardRepository.java
  src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/tutoring/service/TutoringApplyService.java
  src/main/java/com/dongsoop/dongsoop/tutoring/service/TutoringApplyServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/tutoring/service/TutoringBoardService.java
  src/main/java/com/dongsoop/dongsoop/tutoring/service/TutoringBoardServiceImpl.java
  src/test/java/com/dongsoop/dongsoop/notice/NoticeCrawlingTest.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardCreateTest.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardRecruitDateTest.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardStartAtTest.java
Labels: Feature

#32 데이터 생성일자 및 수정일 위치 수정
  src/main/java/com/dongsoop/dongsoop/DongsoopApplication.java
  src/main/java/com/dongsoop/dongsoop/board/Board.java
  src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java
  src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/tutoring/service/TutoringBoardServiceImpl.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardCreateTest.java
Labels: Refactoring

#34 JPA Auditing 설정 위치에 따른 컨트롤러 테스트 실패 문제 개선
  src/main/java/com/dongsoop/dongsoop/DongsoopApplication.java
  src/main/java/com/dongsoop/dongsoop/config/JpaAuditingConfig.java
Labels: bug

#35 사용자 등록 시 학번입력 선택 사항으로 수정
  src/main/java/com/dongsoop/dongsoop/member/dto/SignupRequest.java
Labels: Refactoring

#37 로그인 응답 데이터 추가
  src/main/java/com/dongsoop/dongsoop/member/controller/MemberController.java
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginDetails.java
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginMemberDetails.java
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginResponse.java
  src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
Labels: Refactoring

#38 refactor: modify dto file path in jwt
  src/main/java/com/dongsoop/dongsoop/member/controller/MemberController.java
  src/main/java/com/dongsoop/dongsoop/member/dto/LoginDetails.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
Labels: Refactoring

#41 refactor: Change jwt dto name
  src/main/java/com/dongsoop/dongsoop/jwt/dto/IssuedToken.java
Labels: Refactoring

#42 튜터링 게시글 응답 정보 수정
  src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
  src/main/java/com/dongsoop/dongsoop/tutoring/dto/CreateTutoringBoardRequest.java
  src/main/java/com/dongsoop/dongsoop/tutoring/dto/TutoringBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/tutoring/dto/TutoringBoardOverview.java
  src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/tutoring/service/TutoringBoardServiceImpl.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardCreateTest.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardRecruitDateTest.java
  src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardStartAtTest.java
Labels: bug

#43 회원가입 시 학과 제거
  src/main/java/com/dongsoop/dongsoop/exception/domain/member/InvalidStudentIdFormatException.java
  src/main/java/com/dongsoop/dongsoop/member/dto/SignupRequest.java
  src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
Labels: Refactoring

#44 fix: Change to environment variable
  src/main/resources/logback.xml
Labels: bug

#45 fix: Modifying to the correct path
  src/main/resources/logback.xml
Labels: bug

#48 ci : Adding Pull Request Action Triggers
  .github/workflows/deploy.yml
Labels: Feature

#9 채팅 기능 개발
  build.gradle
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
  src/main/java/com/dongsoop/dongsoop/chat/controller/ChatSocketController.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/CreateGroupRoomRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/CreateRoomRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/KickUserRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/dto/MessageSyncRequest.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatMessage.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatMessageEntity.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoom.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoomEntity.java
  src/main/java/com/dongsoop/dongsoop/chat/entity/MessageType.java
  src/main/java/com/dongsoop/dongsoop/chat/repository/ChatMessageJpaRepository.java
  src/main/java/com/dongsoop/dongsoop/chat/repository/ChatRepository.java
  src/main/java/com/dongsoop/dongsoop/chat/repository/ChatRoomJpaRepository.java
  src/main/java/com/dongsoop/dongsoop/chat/repository/InMemoryChatRepository.java
  src/main/java/com/dongsoop/dongsoop/chat/repository/RedisChatRepository.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatBackupService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
  src/main/java/com/dongsoop/dongsoop/chat/service/ChatSyncService.java
  src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java
  src/main/java/com/dongsoop/dongsoop/config/RedisConfig.java
  src/main/java/com/dongsoop/dongsoop/config/WebSocketConfig.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/websocket/ChatRoomNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/websocket/InvalidChatRequestException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/websocket/ManagerKickAttemptException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/websocket/SelfChatException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/websocket/UnauthorizedChatAccessException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/websocket/UnauthorizedManagerActionException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/websocket/UserKickedException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/websocket/UserNotInRoomException.java
  src/main/java/com/dongsoop/dongsoop/handler/CustomStompErrorHandler.java
  src/main/java/com/dongsoop/dongsoop/handler/StompHandler.java
Labels: Feature

#50 숨겨진(불필요한) 텍스트 크롤링 대상에서 제외
  src/main/java/com/dongsoop/dongsoop/exception/domain/notice/NoticeSubjectNotAvailableException.java
  src/main/java/com/dongsoop/dongsoop/notice/util/NoticeParser.java
Labels: bug

#53 프로젝트 모집 게시판 기능 구현
  src/main/java/com/dongsoop/dongsoop/exception/domain/project/ProjectBoardNotFound.java
  src/main/java/com/dongsoop/dongsoop/project/controller/ProjectBoardController.java
  src/main/java/com/dongsoop/dongsoop/project/dto/CreateProjectBoardRequest.java
  src/main/java/com/dongsoop/dongsoop/project/dto/ProjectBoardDetails.java
  src/main/java/com/dongsoop/dongsoop/project/dto/ProjectBoardOverview.java
  src/main/java/com/dongsoop/dongsoop/project/entity/ProjectBoard.java
  src/main/java/com/dongsoop/dongsoop/project/entity/ProjectBoardApplication.java
  src/main/java/com/dongsoop/dongsoop/project/entity/ProjectBoardDepartment.java
  src/main/java/com/dongsoop/dongsoop/project/repository/ProjectBoardDepartmentRepository.java
  src/main/java/com/dongsoop/dongsoop/project/repository/ProjectBoardRepository.java
  src/main/java/com/dongsoop/dongsoop/project/repository/ProjectBoardRepositoryCustom.java
  src/main/java/com/dongsoop/dongsoop/project/repository/ProjectBoardRepositoryCustomImpl.java
  src/main/java/com/dongsoop/dongsoop/project/service/ProjectBoardService.java
  src/main/java/com/dongsoop/dongsoop/project/service/ProjectBoardServiceImpl.java
  src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectBoardCreateTest.java
  src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectBoardRecruitDateTest.java
  src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectBoardStartAtTest.java
Labels: Feature

#55 금주의 식당 크롤링 & 데이터 제공
  src/main/java/com/dongsoop/dongsoop/exception/domain/meal/MealCleanupException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/meal/MealCrawlingException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/meal/MealNotFoundException.java
  src/main/java/com/dongsoop/dongsoop/exception/domain/meal/MealParsingException.java
  src/main/java/com/dongsoop/dongsoop/meal/controller/MealController.java
  src/main/java/com/dongsoop/dongsoop/meal/dto/MealDailyResponse.java
  src/main/java/com/dongsoop/dongsoop/meal/dto/MealListDto.java
  src/main/java/com/dongsoop/dongsoop/meal/dto/MealWeeklyResponse.java
  src/main/java/com/dongsoop/dongsoop/meal/entity/Meal.java
  src/main/java/com/dongsoop/dongsoop/meal/entity/MealType.java
  src/main/java/com/dongsoop/dongsoop/meal/repository/MealRepository.java
  src/main/java/com/dongsoop/dongsoop/meal/service/MealService.java
  src/main/java/com/dongsoop/dongsoop/meal/service/MealServiceImpl.java
  src/main/java/com/dongsoop/dongsoop/meal/util/DayOfWeekUtil.java
  src/main/java/com/dongsoop/dongsoop/meal/util/MealParser.java
  src/main/java/com/dongsoop/dongsoop/meal/util/TextProcessingUtil.java
  src/main/java/com/dongsoop/dongsoop/meal/util/UrlEncodingUtil.java
Labels: Feature
